### ISSUE TITLE
JOSS Review: Issues with tutorials

### ISSUE THREAD

**Issue by ayush9pandey** [finsberg/gotranx#115]
When running through the [Using the Python API](https://finsberg.github.io/gotranx/examples/run-python/main.html) and the [Your first ODE file](https://finsberg.github.io/gotranx/examples/lorentz.html) page, I am running into a few issues:

1. I don't see a link to the `ORdmm_Land.ode` file. I was able to find it eventually under examples/split-ode/, so it might be better to mention the location on the documentation page. 
2. As a user not familiar with cardiac physiology models, it's difficult to understand the model filename or what it means. This tutorial is placed before the "Your first ODE file", so at this point it is difficult to understand .ode files for new users.
3. Not clear what's printed when I save an ODE file (the number 294). 
![image](https://github.com/user-attachments/assets/b32ddf32-3317-431c-92ea-5ba8469e3fe1)
4. On similar lines as the points above, it might be helpful if there was a tutorial on integrating other ode solver schemes. Maybe this is already given somewhere..

**Comment by finsberg** [comment]
Thanks for your comments. I have now addressed all of these points here: https://github.com/finsberg/gotranx/pull/117
The only exception is point 3. 294 refers to the number of characters written to the file which is the return value from `Path.write_text`. I see two possible ways to fix this
1. Assign the value value to a variable, i.e
```python
num_chars = Path("lorentz.ode").write_text(ode_str)
```
which now introduces an unused variable. Alternatively, I could assign it to `_`, i.e 
```python
_ = Path("lorentz.ode").write_text(ode_str)
```
but I also think this looks a bit weired. 
2. I could write a sentence saying that 294 is just the number of characters. However, I think this also sounds a bit too much. 

Do you have any opinions here?

**Comment by ayush9pandey** [comment]
I agree -- this is not a major issue either way. My approach in the past has been to create a package specific `write_model` function, which in your case could be `write_ode(ode_string, filename)`. That way, you can wrap around the Path library's function and get the desired behavior.

**Comment by finsberg** [comment]
> I agree -- this is not a major issue either way. My approach in the past has been to create a package specific `write_model` function, which in your case could be `write_ode(ode_string, filename)`. That way, you can wrap around the Path library's function and get the desired behavior.

OK, I will just keep it as is. There is already a method for saving an ODE to a file (see https://finsberg.github.io/gotranx/docs/api.html#gotranx.ode.ODE.save). In this case I am simply just writing a string to a file and I see no good reason to why I should make a new function to do exactly the same things (except not returning the number characters written).

**Comment by ayush9pandey** [comment]
OK. So, in principle, I could create an ODE object from the string and then use `save` to save it to a file instead of using the Path library directly?

**Comment by finsberg** [comment]
Yes, there is actually also a function for that, so I updated the example to use that in stead (see https://github.com/finsberg/gotranx/pull/119). Thanks
