### ISSUE TITLE
How to run performance tests

### ISSUE THREAD

**Issue by benlansdell** [finsberg/gotranx#128]
Can the performance tests (`test_benchmarks.py`) be run outside of CI somehow? They're part of the test suite, but seems like it would require the user setup their own codspeed account, is this right? Possibly a some note can be given about how to setup performance tests. Or the github workflow could file be converted to a script a developer could run (with their own codspeed credentials)?

**Comment by finsberg** [comment]
Added more info about this now here: https://github.com/finsberg/gotranx/pull/132

**Comment by finsberg** [comment]
I belive this issue now has been addressed. Feel free to reopen in you disagree.

**Comment by benlansdell** [comment]
Looks good, thanks!
