### ISSUE TITLE
Unit conversion from/to Myokit

### ISSUE THREAD

**Issue by MichaelClerx** [finsberg/gotranx#146]
> It also supports conversion to and from CellML via MyoKit (at the time of writing we still do not support unit conversion from gotranx to MyoKit

Hi @finsberg ! Let me know if you'd like help with this.

And congratulations on the software!

**Comment by finsberg** [comment]
Hi @MichaelClerx! 

Thanks a lot for reaching out and for being willing to help resolving this issue.
I tried to fix this issue this morning and I belive I managed to do so in https://github.com/finsberg/gotranx/pull/147.
I guess the main issue here was that I didn't really allocate time to have a closer look at it 😅
 
Thanks again.
