### ISSUE TITLE
Data sharing-ORdmm_Land.ode file

### ISSUE THREAD

**Issue by SunnyXu** [finsberg/gotranx#95]
Regarding to the requirement from JOSS about the General checks, “Data sharing” is required. The ORdmm_Land.ode file is not provided either under the subsection “Using the Python API” or “Splitting an ODE into two sub-ODEs” or “Compiling a C-extension”. I see it is under examples folder on Github. It would be good to point to the .ode file in the corresponding documentation.

**Comment by finsberg** [comment]
I have now updated the examples with a link to download the `ORdmm_Land.ode` file in https://github.com/finsberg/gotranx/pull/117
