### ISSUE TITLE
 A statement of need in documentation

### ISSUE THREAD

**Issue by SunnyXu** [finsberg/gotranx#97]
Regarding to the requirement from JOSS about the Documentation, “A statement of need” is required. Maybe it has been briefly mentioned in the documentation, however, please add a specific section for it in the documentation.

**Comment by finsberg** [comment]
I have now added an FAQ section in the README, which hopefully address this issue. A full statement of need is found in the paper. Closing this now, but feel free to reopen if you disagree.
